const getActivityCopyDraft = require('../../cloudfunctions/getActivityCopyDraft/index');

function createFakeDb(options = {}) {
  const state = {
    users: {
      openid_owner: { _id: 'openid_owner', roles: ['user', 'organizer'] },
      openid_other: { _id: 'openid_other', roles: ['user', 'organizer'] },
      openid_admin: { _id: 'openid_admin', roles: ['user', 'admin'] },
      openid_super: { _id: 'openid_super', roles: ['user', 'super_admin'] },
      openid_player: { _id: 'openid_player', roles: ['user'] },
      ...(options.users || {})
    },
    activities: {
      activity_1: {
        _id: 'activity_1',
        title: 'Original Match',
        organizerOpenId: 'openid_owner',
        startAt: '2026-04-26T20:00:00.000Z',
        endAt: '2026-04-26T22:00:00.000Z',
        signupDeadlineAt: '2026-04-26T19:30:00.000Z',
        addressText: 'Half Stone',
        addressName: 'Half Stone Football Park',
        location: {
          latitude: 31.2304,
          longitude: 121.4737
        },
        description: 'Bring white and red kits.',
        insuranceLink: 'https://insurance.example.com/apply',
        notificationHint: 'Bring both kits',
        registrationNoticeThreshold: 16,
        coverImage: 'cloud://cover-a',
        coverThumbImage: 'cloud://cover-a-thumb',
        shareImage: 'cloud://share-a',
        imageList: ['cloud://cover-a'],
        detailImages: ['cloud://detail-a', 'cloud://detail-b'],
        signupLimitTotal: 20,
        joinedCount: 7,
        inviteCode: 'PRIVATE',
        status: 'published',
        confirmStatus: 'confirmed',
        confirmedAt: '2026-04-26T15:00:00.000Z',
        confirmedByOpenId: 'openid_owner',
        ...(options.activity || {})
      }
    },
    teams: {
      team_white: {
        _id: 'team_white',
        activityId: 'activity_1',
        teamName: 'White',
        sort: 0,
        maxMembers: 6,
        joinedCount: 4,
        colorKey: 'white',
        teamType: 'regular',
        status: 'active'
      },
      team_red: {
        _id: 'team_red',
        activityId: 'activity_1',
        teamName: 'Red',
        sort: 1,
        maxMembers: 6,
        joinedCount: 3,
        colorKey: 'red',
        teamType: 'regular',
        status: 'active'
      },
      team_bench: {
        _id: 'team_bench',
        activityId: 'activity_1',
        teamName: 'Bench',
        sort: 2,
        maxMembers: 8,
        joinedCount: 0,
        colorKey: 'neutral',
        teamType: 'bench',
        autoGenerated: true,
        status: 'active'
      },
      ...(options.teams || {})
    }
  };

  return {
    state,
    collection(name) {
      return {
        doc(id) {
          return {
            async get() {
              if (name === 'users') {
                return { data: state.users[id] || null };
              }

              if (name === 'activities') {
                return { data: state.activities[id] || null };
              }

              throw new Error(`Unsupported doc lookup: ${name}`);
            }
          };
        },
        where(query) {
          return {
            async get() {
              if (name === 'activity_teams') {
                return {
                  data: Object.values(state.teams).filter(
                    team => team.activityId === query.activityId
                  )
                };
              }

              throw new Error(`Unsupported query: ${name}`);
            }
          };
        }
      };
    }
  };
}

test('organizer can start a copy draft from an activity they manage', async () => {
  const db = createFakeDb();

  const result = await getActivityCopyDraft.main(
    { activityId: 'activity_1' },
    { OPENID: 'openid_owner' },
    { db }
  );

  expect(result.sourceActivityId).toBe('activity_1');
  expect(result.draft).toMatchObject({
    title: 'Original Match',
    addressText: 'Half Stone',
    addressName: 'Half Stone Football Park',
    location: {
      latitude: 31.2304,
      longitude: 121.4737
    },
    description: 'Bring white and red kits.',
    insuranceLink: 'https://insurance.example.com/apply',
    notificationHint: 'Bring both kits',
    registrationNoticeThreshold: 16,
    coverImage: 'cloud://cover-a',
    coverThumbImage: 'cloud://cover-a-thumb',
    shareImage: 'cloud://share-a',
    imageList: ['cloud://cover-a'],
    detailImages: ['cloud://detail-a', 'cloud://detail-b'],
    signupLimitTotal: 20,
    inviteCode: '',
    status: 'draft',
    confirmStatus: 'pending',
    startAt: '',
    endAt: '',
    signupDeadlineAt: '',
    requiresTimeReview: true
  });
  expect(result.draft.teams).toEqual([
    { teamName: 'White', maxMembers: 6, colorKey: 'white' },
    { teamName: 'Red', maxMembers: 6, colorKey: 'red' }
  ]);
});

test('copy draft excludes registrations, attendance, logs, subscription state, and source IDs', async () => {
  const db = createFakeDb();

  const result = await getActivityCopyDraft.main(
    { activityId: 'activity_1' },
    { OPENID: 'openid_owner' },
    { db }
  );

  expect(result.draft).not.toHaveProperty('_id');
  expect(result.draft).not.toHaveProperty('joinedCount');
  expect(result.draft).not.toHaveProperty('confirmedAt');
  expect(result.draft).not.toHaveProperty('confirmedByOpenId');
  expect(result.draft).not.toHaveProperty('requirePhone');
  expect(result.draft).not.toHaveProperty('registrationNotificationSubscribed');
  expect(result.draft).not.toHaveProperty('registrations');
  expect(result.draft).not.toHaveProperty('activityLogs');
  expect(result.draft.teams[0]).not.toHaveProperty('_id');
  expect(result.draft.teams[0]).not.toHaveProperty('joinedCount');
});

test('admin and super admin can copy activities they do not own', async () => {
  const db = createFakeDb();

  await expect(
    getActivityCopyDraft.main(
      { activityId: 'activity_1' },
      { OPENID: 'openid_admin' },
      { db }
    )
  ).resolves.toMatchObject({
    sourceActivityId: 'activity_1'
  });

  await expect(
    getActivityCopyDraft.main(
      { activityId: 'activity_1' },
      { OPENID: 'openid_super' },
      { db }
    )
  ).resolves.toMatchObject({
    sourceActivityId: 'activity_1'
  });
});

test('regular users and other organizers cannot copy an activity', async () => {
  await expect(
    getActivityCopyDraft.main(
      { activityId: 'activity_1' },
      { OPENID: 'openid_player' },
      { db: createFakeDb() }
    )
  ).rejects.toThrow('Only the organizer or an admin can copy this activity');

  await expect(
    getActivityCopyDraft.main(
      { activityId: 'activity_1' },
      { OPENID: 'openid_other' },
      { db: createFakeDb() }
    )
  ).rejects.toThrow('Only the organizer or an admin can copy this activity');
});

test('deleted activities cannot be copied', async () => {
  await expect(
    getActivityCopyDraft.main(
      { activityId: 'activity_1' },
      { OPENID: 'openid_owner' },
      {
        db: createFakeDb({
          activity: {
            status: 'deleted'
          }
        })
      }
    )
  ).rejects.toThrow('Deleted activities cannot be copied');
});
