const { BENCH_TEAM_NAME } = require('../utils/constants');
const { canCreateActivity } = require('../utils/roles');
const { validateActivityDraft } = require('../utils/validators');

function validateSignupPayload(payload) {
  if (!payload.activityId) {
    throw new Error('activityId is required');
  }

  if (!payload.teamId) {
    throw new Error('teamId is required');
  }

  if (!payload.signupName || !payload.signupName.trim()) {
    throw new Error('signupName is required');
  }

  return true;
}

function createDefaultState() {
  return {
    sequence: 1,
    users: {},
    activities: {},
    teams: {},
    registrations: {},
    activityLogs: []
  };
}

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

function buildStorageAdapter(localStorageKey) {
  return {
    getItem(key) {
      try {
        return wx.getStorageSync(key) || null;
      } catch (error) {
        return null;
      }
    },
    setItem(key, value) {
      wx.setStorageSync(key, value);
    },
    removeItem(key) {
      wx.removeStorageSync(key);
    },
    key: localStorageKey
  };
}

function createLocalCloudClient(options = {}) {
  const storage = options.storage;
  const storageKey = options.storageKey || 'football-signup-local-cloud-v1';
  const now = options.now || (() => new Date().toISOString());
  const defaultRoles = Array.isArray(options.defaultRoles)
    ? options.defaultRoles.slice()
    : ['user', 'organizer'];
  const getOpenId = options.openid
    ? () => options.openid
    : () => {
        const cached = storage.getItem(`${storageKey}:openid`);
        if (cached) {
          return cached;
        }

        const created = `mock_openid_${Date.now()}`;
        storage.setItem(`${storageKey}:openid`, created);
        return created;
      };

  function readState() {
    const current = storage.getItem(storageKey);
    return current ? clone(current) : createDefaultState();
  }

  function writeState(state) {
    storage.setItem(storageKey, clone(state));
  }

  function nextId(state, prefix) {
    const id = `${prefix}_${state.sequence}`;
    state.sequence += 1;
    return id;
  }

  function buildDefaultUser(openid, stamp) {
    return {
      _id: openid,
      preferredName: '',
      avatarUrl: '',
      roles: defaultRoles.slice(),
      createdAt: stamp,
      lastActiveAt: stamp
    };
  }

  function ensureUserInState(state, openid, stamp) {
    if (!state.users[openid]) {
      state.users[openid] = buildDefaultUser(openid, stamp);
    }

    return state.users[openid];
  }

  function ensureUserProfile() {
    const state = readState();
    const openid = getOpenId();
    const stamp = now();
    const current = state.users[openid];

    if (current) {
      current.lastActiveAt = stamp;
      writeState(state);
      return { user: clone(current) };
    }

    const user = buildDefaultUser(openid, stamp);

    state.users[openid] = user;
    writeState(state);
    return { user: clone(user) };
  }

  function createActivity(payload) {
    validateActivityDraft(payload);
    const state = readState();
    const stamp = now();
    const openid = getOpenId();
    const user = ensureUserInState(state, openid, stamp);

    if (!canCreateActivity(user)) {
      throw new Error('Only organizers can create activities');
    }

    const activityId = nextId(state, 'activity');
    const regularTeams = payload.teams.map((team, index) => ({
      teamName: team.teamName.trim(),
      sort: index,
      maxMembers: Number(team.maxMembers) || 0,
      teamType: 'regular',
      autoGenerated: false
    }));
    const regularTeamSlots = regularTeams.reduce((sum, team) => sum + team.maxMembers, 0);
    const benchSlots = Math.max((Number(payload.signupLimitTotal) || 0) - regularTeamSlots, 0);
    const imageList = Array.isArray(payload.imageList)
      ? payload.imageList.filter(Boolean)
      : payload.coverImage
        ? [payload.coverImage]
        : [];

    if (benchSlots > 0) {
      regularTeams.push({
        teamName: '替补',
        sort: regularTeams.length,
        maxMembers: benchSlots,
        teamType: 'bench',
        autoGenerated: true
      });
    }

    const teamsForStorage = regularTeams.map(team =>
      team.teamType === 'bench' ? { ...team, teamName: BENCH_TEAM_NAME } : team
    );

    state.activities[activityId] = {
      _id: activityId,
      title: payload.title.trim(),
      organizerOpenId: openid,
      startAt: payload.startAt,
      endAt: payload.endAt,
      signupDeadlineAt: payload.signupDeadlineAt,
      addressText: payload.addressText.trim(),
      addressName: payload.addressName || payload.addressText.trim(),
      location: payload.location || null,
      description: payload.description || '',
      coverImage: imageList[0] || payload.coverImage || '',
      imageList,
      signupLimitTotal: Number(payload.signupLimitTotal) || 0,
      joinedCount: 0,
      requirePhone: Boolean(payload.requirePhone),
      inviteCode: payload.inviteCode || '',
      feeMode: 'free',
      status: 'published',
      createdAt: stamp,
      updatedAt: stamp
    };

    teamsForStorage.forEach((team, index) => {
      const teamId = nextId(state, 'team');
      state.teams[teamId] = {
        _id: teamId,
        activityId,
        teamName: team.teamName,
        sort: index,
        maxMembers: team.maxMembers,
        joinedCount: 0,
        teamType: team.teamType,
        autoGenerated: team.autoGenerated,
        status: 'active',
        createdAt: stamp
      };
    });

    state.activityLogs[nextId(state, 'log')] = {
      activityId,
      operatorOpenId: openid,
      action: 'create_activity',
      createdAt: stamp
    };

    writeState(state);
    return { activityId };
  }

function listActivities(payload) {
    const state = readState();
    const openid = getOpenId();
    const activities = Object.values(state.activities);

    if (payload.scope === 'home') {
      return {
        items: clone(
          activities.filter(item => item.status === 'published' || item.status === 'cancelled')
        )
      };
    }

    if (payload.scope === 'created') {
      return {
        items: clone(activities.filter(item => item.organizerOpenId === openid))
      };
    }

    if (payload.scope === 'joined') {
      const joinedIds = new Set(
        Object.values(state.registrations)
          .filter(item => item.userOpenId === openid && item.status === 'joined')
          .map(item => item.activityId)
      );

      return {
        items: clone(activities.filter(item => joinedIds.has(item._id) && item.status !== 'deleted'))
      };
    }

    return {
      items: clone(activities.filter(item => item.status === (payload.status || 'published')))
    };
  }

  function getActivityDetail(payload) {
    const state = readState();
    const openid = getOpenId();
    const activity = state.activities[payload.activityId];

    if (!activity) {
      throw new Error('Activity not found');
    }

    if (activity.status === 'deleted' && activity.organizerOpenId !== openid) {
      throw new Error('Activity not found');
    }

    const teams = Object.values(state.teams)
      .filter(team => team.activityId === payload.activityId)
      .sort((left, right) => left.sort - right.sort)
      .map(team => {
        const members = Object.values(state.registrations)
          .filter(item => item.activityId === payload.activityId && item.teamId === team._id && item.status === 'joined')
          .sort((left, right) => String(left.joinedAt).localeCompare(String(right.joinedAt)))
          .map(item => ({
            userOpenId: item.userOpenId,
            signupName: item.signupName,
            avatarUrl: (state.users[item.userOpenId] && state.users[item.userOpenId].avatarUrl) || ''
          }));

        return {
          ...team,
          members
        };
      });
    const current = state.registrations[`${payload.activityId}_${openid}`] || null;
    const deadline = Date.parse(activity.signupDeadlineAt || '');
    const canCancelSignup = Boolean(
      current &&
        current.status === 'joined' &&
        activity.status === 'published' &&
        (!Number.isFinite(deadline) || Date.parse(now()) <= deadline)
    );

    return {
      activity: clone(activity),
      teams: clone(teams),
      myRegistration: clone(current),
      viewer: {
        isOrganizer: activity.organizerOpenId === openid,
        canCancelActivity: activity.organizerOpenId === openid && activity.status === 'published',
        canDeleteActivity: activity.organizerOpenId === openid && Number(activity.joinedCount) === 0,
        canCancelSignup
      }
    };
  }

  function joinActivity(payload) {
    validateSignupPayload(payload);
    const state = readState();
    const openid = getOpenId();
    const stamp = now();
    const activity = state.activities[payload.activityId];
    const team = state.teams[payload.teamId];
    const registrationId = `${payload.activityId}_${openid}`;
    const current = state.registrations[registrationId];

    if (!activity || activity.status !== 'published') {
      throw new Error('Activity is not open for signup');
    }

    const deadline = Date.parse(activity.signupDeadlineAt || '');
    if (Number.isFinite(deadline) && Date.parse(stamp) > deadline) {
      throw new Error('Signup is closed');
    }

    if (!team) {
      throw new Error('Team not found');
    }

    if (activity.joinedCount >= activity.signupLimitTotal) {
      throw new Error('Activity is full');
    }

    if (team.joinedCount >= team.maxMembers) {
      throw new Error('Team is full');
    }

    if (current && current.status === 'joined') {
      throw new Error('You already joined this activity');
    }

    const user = ensureUserInState(state, openid, stamp);
    user.preferredName = payload.signupName.trim();
    user.lastActiveAt = stamp;

    state.registrations[registrationId] = {
      _id: registrationId,
      activityId: payload.activityId,
      teamId: payload.teamId,
      userOpenId: openid,
      status: 'joined',
      signupName: payload.signupName.trim(),
      phoneSnapshot: payload.phone || '',
      source: payload.source || 'direct',
      joinedAt: stamp,
      cancelledAt: current ? current.cancelledAt || '' : '',
      updatedAt: stamp
    };

    activity.joinedCount += 1;
    activity.updatedAt = stamp;
    team.joinedCount += 1;
    writeState(state);

    return {
      registrationId,
      teamId: payload.teamId,
      status: 'joined'
    };
  }

  function cancelRegistration(payload) {
    const state = readState();
    const openid = getOpenId();
    const stamp = now();
    const registrationId = `${payload.activityId}_${openid}`;
    const current = state.registrations[registrationId];

    if (!current || current.status !== 'joined') {
      throw new Error('No active registration to cancel');
    }

    const activity = state.activities[payload.activityId];
    const team = state.teams[current.teamId];

    if (activity.status !== 'published') {
      throw new Error('Signup can no longer be cancelled');
    }

    const deadline = Date.parse(activity.signupDeadlineAt || '');
    if (Number.isFinite(deadline) && Date.parse(stamp) > deadline) {
      throw new Error('Signup can no longer be cancelled');
    }

    current.status = 'cancelled';
    current.cancelledAt = stamp;
    current.updatedAt = stamp;
    activity.joinedCount = Math.max(activity.joinedCount - 1, 0);
    activity.updatedAt = stamp;
    team.joinedCount = Math.max(team.joinedCount - 1, 0);

    writeState(state);
    return {
      registrationId,
      status: 'cancelled'
    };
  }

  function cancelActivity(payload) {
    const state = readState();
    const openid = getOpenId();
    const stamp = now();
    const activity = state.activities[payload.activityId];

    if (!activity) {
      throw new Error('Activity not found');
    }

    if (activity.organizerOpenId !== openid) {
      throw new Error('Only the organizer can cancel this activity');
    }

    activity.status = 'cancelled';
    activity.updatedAt = stamp;
    writeState(state);

    return {
      activityId: payload.activityId,
      status: 'cancelled'
    };
  }

  function deleteActivity(payload) {
    const state = readState();
    const openid = getOpenId();
    const stamp = now();
    const activity = state.activities[payload.activityId];

    if (!activity) {
      throw new Error('Activity not found');
    }

    if (activity.organizerOpenId !== openid) {
      throw new Error('Only the organizer can delete this activity');
    }

    if (Number(activity.joinedCount) > 0) {
      throw new Error('Only activities without joined players can be deleted');
    }

    activity.status = 'deleted';
    activity.updatedAt = stamp;

    writeState(state);
    return {
      activityId: payload.activityId,
      status: 'deleted'
    };
  }

  function getActivityStats(payload) {
    const state = readState();
    const openid = getOpenId();
    const activity = state.activities[payload.activityId];

    if (!activity || activity.organizerOpenId !== openid) {
      throw new Error('Not allowed to view activity stats');
    }

    const registrations = Object.values(state.registrations).filter(
      item => item.activityId === payload.activityId
    );
    const teams = Object.values(state.teams)
      .filter(team => team.activityId === payload.activityId)
      .sort((left, right) => left.sort - right.sort);

    return {
      activityId: payload.activityId,
      totalJoined: registrations.filter(item => item.status === 'joined').length,
      totalCancelled: registrations.filter(item => item.status === 'cancelled').length,
      teams: teams.map(team => ({
        teamId: team._id,
        teamName: team.teamName,
        joinedCount: team.joinedCount,
        maxMembers: team.maxMembers
      }))
    };
  }

  const handlers = {
    ensureUserProfile,
    createActivity,
    listActivities,
    getActivityDetail,
    joinActivity,
    cancelRegistration,
    cancelActivity,
    deleteActivity,
    getActivityStats
  };

  return {
    call(name, payload = {}) {
      const handler = handlers[name];
      if (!handler) {
        return Promise.reject(new Error(`Unknown local cloud function: ${name}`));
      }

      try {
        return Promise.resolve(handler(payload));
      } catch (error) {
        return Promise.reject(error);
      }
    }
  };
}

module.exports = {
  buildStorageAdapter,
  createLocalCloudClient
};
