const cloud = require('wx-server-sdk');
const { resolveOpenId } = require('./auth');
const { COLLECTIONS } = require('./collections');
const { businessError } = require('./errors');
const { canCreateActivity } = require('./roles');
const { normalizeTeamColorKey } = require('./team-colors');
const { nowIso } = require('./time');
const { normalizeActivityType, validateActivityDraft } = require('./validators');

const BENCH_TEAM_NAME = '\u66ff\u8865';

cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV });

function hasExplicitBenchCapacity(event) {
  return event.benchCapacity !== undefined && event.benchCapacity !== null && event.benchCapacity !== '';
}

function normalizeCapacity(value) {
  const capacity = Number(value || 0);
  return Number.isFinite(capacity) && capacity > 0 ? Math.floor(capacity) : 0;
}

function getRegularTeamSlots(teams = []) {
  return teams.reduce((sum, team) => sum + normalizeCapacity(team.maxMembers), 0);
}

function getBenchCapacity(event, regularSlots) {
  if (hasExplicitBenchCapacity(event)) {
    return normalizeCapacity(event.benchCapacity);
  }

  return Math.max(normalizeCapacity(event.signupLimitTotal) - regularSlots, 0);
}

function getComputedSignupLimitTotal(event) {
  const regularSlots = getRegularTeamSlots(Array.isArray(event.teams) ? event.teams : []);
  return regularSlots + getBenchCapacity(event, regularSlots);
}

function buildTeamDrafts(event, signupLimitTotal) {
  const regularTeams = event.teams.map((team, index) => ({
    teamName: team.teamName.trim(),
    sort: index,
    maxMembers: Number(team.maxMembers) || 0,
    colorKey: normalizeTeamColorKey(team.colorKey, index),
    teamType: 'regular',
    autoGenerated: false
  }));
  const teamSlots = regularTeams.reduce((sum, team) => sum + team.maxMembers, 0);
  const benchSlots = Math.max((Number(signupLimitTotal) || 0) - teamSlots, 0);

  if (benchSlots > 0) {
    regularTeams.push({
      teamName: BENCH_TEAM_NAME,
      sort: regularTeams.length,
      maxMembers: benchSlots,
      colorKey: 'neutral',
      teamType: 'bench',
      autoGenerated: true
    });
  }

  return regularTeams;
}

function getDefaultRegistrationNoticeThreshold(signupLimitTotal) {
  const total = Number(signupLimitTotal) || 0;
  return total > 0 ? Math.ceil(total * 0.8) : 0;
}

function normalizeRegistrationNoticeThreshold(value, signupLimitTotal) {
  const threshold = Number(value || 0);

  if (Number.isFinite(threshold) && threshold > 0) {
    return Math.floor(threshold);
  }

  return getDefaultRegistrationNoticeThreshold(signupLimitTotal);
}

async function getCurrentUser(db, openid) {
  const result = await db
    .collection(COLLECTIONS.USERS)
    .doc(openid)
    .get()
    .catch(() => ({ data: null }));

  return result.data || null;
}

async function assertCanCreateActivity(db, openid) {
  const user = await getCurrentUser(db, openid);

  if (!canCreateActivity(user)) {
    throw businessError('Only organizers can create activities');
  }
}

async function main(event, context = cloud.getWXContext(), deps = {}) {
  const db = deps.db || cloud.database();
  const openid = resolveOpenId(context, deps.getWXContext || (() => cloud.getWXContext()));
  await assertCanCreateActivity(db, openid);
  const signupLimitTotal = getComputedSignupLimitTotal(event);
  validateActivityDraft({
    ...event,
    signupLimitTotal
  });
  const teams = buildTeamDrafts(event, signupLimitTotal);

  const stamp = nowIso(deps.now);
  const imageList = Array.isArray(event.imageList)
    ? event.imageList.filter(Boolean)
    : event.coverImage
      ? [event.coverImage]
      : [];
  const detailImages = Array.isArray(event.detailImages)
    ? event.detailImages.filter(Boolean)
    : [];

  const activityData = {
    title: event.title.trim(),
    activityType: normalizeActivityType(event.activityType),
    organizerOpenId: openid,
    startAt: event.startAt,
    endAt: event.endAt,
    signupDeadlineAt: event.signupDeadlineAt,
    addressText: event.addressText.trim(),
    addressName: event.addressName || event.addressText.trim(),
    location: event.location || null,
    description: event.description || '',
    insuranceLink: String(event.insuranceLink || '').trim(),
    notificationHint: String(event.notificationHint || '').trim(),
    registrationNoticeThreshold: normalizeRegistrationNoticeThreshold(
      event.registrationNoticeThreshold,
      signupLimitTotal
    ),
    coverImage: imageList[0] || event.coverImage || '',
    coverThumbImage: event.coverThumbImage || '',
    shareImage: event.shareImage || '',
    imageList,
    detailImages,
    signupLimitTotal,
    joinedCount: 0,
    requirePhone: false,
    inviteCode: event.inviteCode || '',
    feeMode: 'free',
    status: 'published',
    confirmStatus: 'pending',
    confirmedAt: '',
    confirmedByOpenId: '',
    createdAt: stamp,
    updatedAt: stamp
  };

  const activityRes = await db.collection('activities').add({ data: activityData });

  for (let index = 0; index < teams.length; index += 1) {
    await db.collection('activity_teams').add({
      data: {
        activityId: activityRes._id,
        teamName: teams[index].teamName,
        sort: teams[index].sort,
        maxMembers: teams[index].maxMembers,
        colorKey: teams[index].colorKey,
        joinedCount: 0,
        teamType: teams[index].teamType,
        autoGenerated: teams[index].autoGenerated,
        status: 'active',
        createdAt: stamp
      }
    });
  }

  return { activityId: activityRes._id };
}

module.exports = { main };
