const cloud = require('wx-server-sdk');
const { resolveOpenId } = require('./auth');
const { COLLECTIONS } = require('./collections');
const { businessError } = require('./errors');
const { canCreateActivity } = require('./roles');
const { nowIso } = require('./time');
const { validateActivityDraft } = require('./validators');

const BENCH_TEAM_NAME = '\u66ff\u8865';

cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV });

function buildTeamDrafts(event) {
  const regularTeams = event.teams.map((team, index) => ({
    teamName: team.teamName.trim(),
    sort: index,
    maxMembers: Number(team.maxMembers) || 0,
    teamType: 'regular',
    autoGenerated: false
  }));
  const teamSlots = regularTeams.reduce((sum, team) => sum + team.maxMembers, 0);
  const benchSlots = Math.max((Number(event.signupLimitTotal) || 0) - teamSlots, 0);

  if (benchSlots > 0) {
    regularTeams.push({
      teamName: BENCH_TEAM_NAME,
      sort: regularTeams.length,
      maxMembers: benchSlots,
      teamType: 'bench',
      autoGenerated: true
    });
  }

  return regularTeams;
}

async function getCurrentUser(db, openid) {
  const result = await db
    .collection(COLLECTIONS.USERS)
    .doc(openid)
    .get()
    .catch(() => ({ data: null }));

  return result.data || null;
}

async function assertCanCreateActivity(db, openid) {
  const user = await getCurrentUser(db, openid);

  if (!canCreateActivity(user)) {
    throw businessError('Only organizers can create activities');
  }
}

async function main(event, context = cloud.getWXContext(), deps = {}) {
  const db = deps.db || cloud.database();
  const openid = resolveOpenId(context, deps.getWXContext || (() => cloud.getWXContext()));
  await assertCanCreateActivity(db, openid);
  validateActivityDraft(event);
  const teams = buildTeamDrafts(event);

  const stamp = nowIso(deps.now);
  const imageList = Array.isArray(event.imageList)
    ? event.imageList.filter(Boolean)
    : event.coverImage
      ? [event.coverImage]
      : [];

  const activityData = {
    title: event.title.trim(),
    organizerOpenId: openid,
    startAt: event.startAt,
    endAt: event.endAt,
    signupDeadlineAt: event.signupDeadlineAt,
    addressText: event.addressText.trim(),
    addressName: event.addressName || event.addressText.trim(),
    location: event.location || null,
    description: event.description || '',
    insuranceLink: String(event.insuranceLink || '').trim(),
    coverImage: imageList[0] || event.coverImage || '',
    coverThumbImage: event.coverThumbImage || '',
    imageList,
    signupLimitTotal: Number(event.signupLimitTotal) || 0,
    joinedCount: 0,
    requirePhone: false,
    inviteCode: event.inviteCode || '',
    feeMode: 'free',
    status: 'published',
    createdAt: stamp,
    updatedAt: stamp
  };

  const activityRes = await db.collection('activities').add({ data: activityData });

  for (let index = 0; index < teams.length; index += 1) {
    await db.collection('activity_teams').add({
      data: {
        activityId: activityRes._id,
        teamName: teams[index].teamName,
        sort: teams[index].sort,
        maxMembers: teams[index].maxMembers,
        joinedCount: 0,
        teamType: teams[index].teamType,
        autoGenerated: teams[index].autoGenerated,
        status: 'active',
        createdAt: stamp
      }
    });
  }

  return { activityId: activityRes._id };
}

module.exports = { main };
