const cloud = require('wx-server-sdk');
const { resolveOpenId } = require('./auth');
const { COLLECTIONS } = require('./collections');
const { businessError } = require('./errors');
const { canEditActivity } = require('./roles');
const { normalizeTeamColorKey } = require('./team-colors');
const { nowIso } = require('./time');
const { normalizeActivityType, validateActivityDraft } = require('./validators');

const BENCH_TEAM_NAME = '\u66ff\u8865';

cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV });

async function getCurrentUser(db, openid) {
  const result = await db
    .collection(COLLECTIONS.USERS)
    .doc(openid)
    .get()
    .catch(() => ({ data: null }));

  return result.data || null;
}

function normalizeImageList(event) {
  if (Array.isArray(event.imageList)) {
    return event.imageList.filter(Boolean);
  }

  return event.coverImage ? [event.coverImage] : [];
}

function normalizeDetailImages(event) {
  return Array.isArray(event.detailImages) ? event.detailImages.filter(Boolean) : [];
}

function getRegularTeams(teams) {
  return teams
    .filter(team => team.status !== 'inactive' && team.teamType !== 'bench')
    .sort((left, right) => Number(left.sort || 0) - Number(right.sort || 0));
}

function buildRegularTeamDrafts(event, existingRegularTeams) {
  const sourceTeams = Array.isArray(event.teams) ? event.teams : existingRegularTeams;

  return sourceTeams.map((team, index) => ({
    _id: String(team._id || '').trim(),
    teamName: String(team.teamName || '').trim(),
    sort: index,
    maxMembers: Number(team.maxMembers) || 0,
    colorKey: normalizeTeamColorKey(team.colorKey, index),
    teamType: 'regular',
    autoGenerated: false
  }));
}

function buildValidationDraft(event, regularTeamDrafts) {
  return {
    ...event,
    teams: regularTeamDrafts.map(team => ({
      teamName: team.teamName,
      maxMembers: Number(team.maxMembers) || 0
    }))
  };
}

function resolveAddressName(event, activity, addressText) {
  const addressName = String(event.addressName || '').trim();
  const previousAddressName = String(activity.addressName || '').trim();
  const previousAddressText = String(activity.addressText || '').trim();
  const addressTextChanged = addressText !== previousAddressText;
  const staleAddressName =
    addressTextChanged &&
    addressName &&
    addressName === previousAddressName &&
    !event.location;

  if (staleAddressName) {
    return addressText;
  }

  return addressName || addressText;
}

function getDefaultRegistrationNoticeThreshold(signupLimitTotal) {
  const total = Number(signupLimitTotal) || 0;
  return total > 0 ? Math.ceil(total * 0.8) : 0;
}

function normalizeRegistrationNoticeThreshold(value, signupLimitTotal) {
  const threshold = Number(value || 0);

  if (Number.isFinite(threshold) && threshold > 0) {
    return Math.floor(threshold);
  }

  return getDefaultRegistrationNoticeThreshold(signupLimitTotal);
}

function buildActivityUpdateData(event, activity, stamp) {
  const imageList = normalizeImageList(event);
  const detailImages = normalizeDetailImages(event);
  const title = String(event.title || '').trim();
  const addressText = String(event.addressText || '').trim();

  return {
    title,
    activityType: normalizeActivityType(event.activityType),
    startAt: event.startAt,
    endAt: event.endAt,
    signupDeadlineAt: event.signupDeadlineAt,
    addressText,
    addressName: resolveAddressName(event, activity, addressText),
    location: event.location || null,
    description: event.description || '',
    insuranceLink: String(event.insuranceLink || '').trim(),
    notificationHint: String(event.notificationHint || '').trim(),
    registrationNoticeThreshold: normalizeRegistrationNoticeThreshold(
      event.registrationNoticeThreshold,
      event.signupLimitTotal
    ),
    coverImage: imageList[0] || event.coverImage || '',
    coverThumbImage: event.coverThumbImage || '',
    shareImage: event.shareImage || '',
    imageList,
    detailImages,
    signupLimitTotal: Number(event.signupLimitTotal) || 0,
    requirePhone: false,
    inviteCode: event.inviteCode || '',
    updatedAt: stamp
  };
}

function replaceFieldValue(db, value) {
  if (db && db.command && typeof db.command.set === 'function') {
    return db.command.set(value);
  }

  return value;
}

function buildDatabaseUpdateData(db, updateData) {
  return {
    ...updateData,
    location: replaceFieldValue(db, updateData.location)
  };
}

function getChangedFields(activity, updateData) {
  return Object.keys(updateData).filter(field => {
    if (field === 'updatedAt') {
      return false;
    }

    return JSON.stringify(activity[field] === undefined ? null : activity[field]) !==
      JSON.stringify(updateData[field] === undefined ? null : updateData[field]);
  });
}

function assertRegularTeamUpdatesAllowed(existingRegularTeams, regularTeamDrafts) {
  const existingById = new Map(existingRegularTeams.map(team => [team._id, team]));
  const seenIds = new Set();

  regularTeamDrafts.forEach(team => {
    if (!team._id) {
      return;
    }

    if (seenIds.has(team._id)) {
      throw businessError('Duplicate team id');
    }

    seenIds.add(team._id);
    const existing = existingById.get(team._id);

    if (!existing) {
      throw businessError('Team not found');
    }

    if (Number(team.maxMembers || 0) < Number(existing.joinedCount || 0)) {
      throw businessError('Team capacity cannot be lower than joined members');
    }
  });

  existingRegularTeams.forEach(team => {
    if (seenIds.has(team._id)) {
      return;
    }

    if (Number(team.joinedCount || 0) > 0) {
      throw businessError('Teams with joined members cannot be removed');
    }
  });
}

function hasRegularTeamChanged(existing, draft) {
  return (
    String(existing.teamName || '') !== draft.teamName ||
    Number(existing.maxMembers || 0) !== Number(draft.maxMembers || 0) ||
    String(existing.colorKey || '') !== draft.colorKey ||
    Number(existing.sort || 0) !== Number(draft.sort || 0) ||
    existing.status === 'inactive'
  );
}

async function syncRegularTeams(db, activityId, existingRegularTeams, regularTeamDrafts, stamp) {
  const existingById = new Map(existingRegularTeams.map(team => [team._id, team]));
  const keptIds = new Set();
  let changed = false;

  for (let index = 0; index < regularTeamDrafts.length; index += 1) {
    const draft = regularTeamDrafts[index];

    if (draft._id) {
      const existing = existingById.get(draft._id);
      keptIds.add(draft._id);

      if (hasRegularTeamChanged(existing, draft)) {
        changed = true;
        await db.collection(COLLECTIONS.ACTIVITY_TEAMS).doc(draft._id).update({
          data: {
            teamName: draft.teamName,
            sort: draft.sort,
            maxMembers: draft.maxMembers,
            colorKey: draft.colorKey,
            teamType: 'regular',
            autoGenerated: false,
            status: 'active',
            updatedAt: stamp
          }
        });
      }
      continue;
    }

    changed = true;
    await db.collection(COLLECTIONS.ACTIVITY_TEAMS).add({
      data: {
        activityId,
        teamName: draft.teamName,
        sort: index,
        maxMembers: draft.maxMembers,
        colorKey: draft.colorKey,
        joinedCount: 0,
        teamType: 'regular',
        autoGenerated: false,
        status: 'active',
        createdAt: stamp
      }
    });
  }

  for (let index = 0; index < existingRegularTeams.length; index += 1) {
    const existing = existingRegularTeams[index];

    if (keptIds.has(existing._id)) {
      continue;
    }

    changed = true;
    await db.collection(COLLECTIONS.ACTIVITY_TEAMS).doc(existing._id).update({
      data: {
        status: 'inactive',
        updatedAt: stamp
      }
    });
  }

  return changed;
}

async function syncBenchTeam(db, activityId, teams, regularTeams, totalSignupLimit, stamp) {
  const regularSlots = regularTeams.reduce((sum, team) => sum + (Number(team.maxMembers) || 0), 0);
  const benchSlots = Math.max(totalSignupLimit - regularSlots, 0);
  const benchTeam = teams.find(team => team.teamType === 'bench');

  if (benchTeam && benchSlots < Number(benchTeam.joinedCount || 0)) {
    throw businessError('Total signup limit cannot be lower than joined players');
  }

  if (benchTeam) {
    await db.collection(COLLECTIONS.ACTIVITY_TEAMS).doc(benchTeam._id).update({
      data: {
        maxMembers: benchSlots,
        status: benchSlots > 0 || Number(benchTeam.joinedCount || 0) > 0 ? 'active' : 'inactive',
        updatedAt: stamp
      }
    });
    return;
  }

  if (benchSlots > 0) {
    await db.collection(COLLECTIONS.ACTIVITY_TEAMS).add({
      data: {
        activityId,
        teamName: BENCH_TEAM_NAME,
        sort: regularTeams.length,
        maxMembers: benchSlots,
        colorKey: 'neutral',
        joinedCount: 0,
        teamType: 'bench',
        autoGenerated: true,
        status: 'active',
        createdAt: stamp
      }
    });
  }
}

async function main(event, context = cloud.getWXContext(), deps = {}) {
  if (!event.activityId) {
    throw businessError('activityId is required');
  }

  const db = deps.db || cloud.database();
  const openid = resolveOpenId(context, deps.getWXContext || (() => cloud.getWXContext()));
  const activityResult = await db.collection(COLLECTIONS.ACTIVITIES).doc(event.activityId).get();
  const activity = activityResult.data;

  if (!activity) {
    throw businessError('Activity not found');
  }

  if (activity.status === 'deleted') {
    throw businessError('Deleted activities cannot be edited');
  }

  const user = await getCurrentUser(db, openid);
  if (!canEditActivity(activity, user, openid)) {
    throw businessError('Only the organizer or an admin can edit this activity');
  }

  const teamsResult = await db
    .collection(COLLECTIONS.ACTIVITY_TEAMS)
    .where({ activityId: event.activityId })
    .get();
  const teams = teamsResult.data || [];
  const regularTeams = getRegularTeams(teams);
  const regularTeamDrafts = buildRegularTeamDrafts(event, regularTeams);
  const updateData = buildActivityUpdateData(event, activity, nowIso(deps.now));

  if (Number(updateData.signupLimitTotal) < Number(activity.joinedCount || 0)) {
    throw businessError('Total signup limit cannot be lower than joined players');
  }

  validateActivityDraft(buildValidationDraft(updateData, regularTeamDrafts));
  assertRegularTeamUpdatesAllowed(regularTeams, regularTeamDrafts);

  await syncBenchTeam(
    db,
    event.activityId,
    teams,
    regularTeamDrafts,
    Number(updateData.signupLimitTotal) || 0,
    updateData.updatedAt
  );

  const teamsChanged = await syncRegularTeams(
    db,
    event.activityId,
    regularTeams,
    regularTeamDrafts,
    updateData.updatedAt
  );

  await db.collection(COLLECTIONS.ACTIVITIES).doc(event.activityId).update({
    data: buildDatabaseUpdateData(db, updateData)
  });

  const changedFields = getChangedFields(activity, updateData);
  if (teamsChanged) {
    changedFields.push('teams');
  }
  await db.collection(COLLECTIONS.ACTIVITY_LOGS).add({
    data: {
      activityId: event.activityId,
      operatorOpenId: openid,
      action: 'update_activity',
      changedFields,
      createdAt: updateData.updatedAt
    }
  });

  return {
    activityId: event.activityId,
    updated: true,
    changedFields
  };
}

module.exports = { main };
