const cloud = require('wx-server-sdk');
const { resolveOpenId } = require('./auth');
const { COLLECTIONS } = require('./collections');
const { businessError } = require('./errors');
const { canEditActivity } = require('./roles');
const { nowIso } = require('./time');
const { validateActivityDraft } = require('./validators');

const BENCH_TEAM_NAME = '\u66ff\u8865';

cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV });

async function getCurrentUser(db, openid) {
  const result = await db
    .collection(COLLECTIONS.USERS)
    .doc(openid)
    .get()
    .catch(() => ({ data: null }));

  return result.data || null;
}

function normalizeImageList(event) {
  if (Array.isArray(event.imageList)) {
    return event.imageList.filter(Boolean);
  }

  return event.coverImage ? [event.coverImage] : [];
}

function getRegularTeams(teams) {
  return teams
    .filter(team => team.status !== 'inactive' && team.teamType !== 'bench')
    .sort((left, right) => Number(left.sort || 0) - Number(right.sort || 0));
}

function buildValidationDraft(event, regularTeams) {
  return {
    ...event,
    teams: regularTeams.map(team => ({
      teamName: team.teamName,
      maxMembers: Number(team.maxMembers) || 0
    }))
  };
}

function resolveAddressName(event, activity, addressText) {
  const addressName = String(event.addressName || '').trim();
  const previousAddressName = String(activity.addressName || '').trim();
  const previousAddressText = String(activity.addressText || '').trim();
  const addressTextChanged = addressText !== previousAddressText;
  const staleAddressName =
    addressTextChanged &&
    addressName &&
    addressName === previousAddressName &&
    !event.location;

  if (staleAddressName) {
    return addressText;
  }

  return addressName || addressText;
}

function buildActivityUpdateData(event, activity, stamp) {
  const imageList = normalizeImageList(event);
  const title = String(event.title || '').trim();
  const addressText = String(event.addressText || '').trim();

  return {
    title,
    startAt: event.startAt,
    endAt: event.endAt,
    signupDeadlineAt: event.signupDeadlineAt,
    addressText,
    addressName: resolveAddressName(event, activity, addressText),
    location: event.location || null,
    description: event.description || '',
    coverImage: imageList[0] || event.coverImage || '',
    coverThumbImage: event.coverThumbImage || '',
    imageList,
    signupLimitTotal: Number(event.signupLimitTotal) || 0,
    requirePhone: false,
    inviteCode: event.inviteCode || '',
    updatedAt: stamp
  };
}

function replaceFieldValue(db, value) {
  if (db && db.command && typeof db.command.set === 'function') {
    return db.command.set(value);
  }

  return value;
}

function buildDatabaseUpdateData(db, updateData) {
  return {
    ...updateData,
    location: replaceFieldValue(db, updateData.location)
  };
}

function getChangedFields(activity, updateData) {
  return Object.keys(updateData).filter(field => {
    if (field === 'updatedAt') {
      return false;
    }

    return JSON.stringify(activity[field] === undefined ? null : activity[field]) !==
      JSON.stringify(updateData[field] === undefined ? null : updateData[field]);
  });
}

async function syncBenchTeam(db, activityId, teams, totalSignupLimit, stamp) {
  const regularTeams = getRegularTeams(teams);
  const regularSlots = regularTeams.reduce((sum, team) => sum + (Number(team.maxMembers) || 0), 0);
  const benchSlots = Math.max(totalSignupLimit - regularSlots, 0);
  const benchTeam = teams.find(team => team.teamType === 'bench');

  if (benchTeam && benchSlots < Number(benchTeam.joinedCount || 0)) {
    throw businessError('Total signup limit cannot be lower than joined players');
  }

  if (benchTeam) {
    await db.collection(COLLECTIONS.ACTIVITY_TEAMS).doc(benchTeam._id).update({
      data: {
        maxMembers: benchSlots,
        status: benchSlots > 0 || Number(benchTeam.joinedCount || 0) > 0 ? 'active' : 'inactive',
        updatedAt: stamp
      }
    });
    return;
  }

  if (benchSlots > 0) {
    await db.collection(COLLECTIONS.ACTIVITY_TEAMS).add({
      data: {
        activityId,
        teamName: BENCH_TEAM_NAME,
        sort: regularTeams.length,
        maxMembers: benchSlots,
        joinedCount: 0,
        teamType: 'bench',
        autoGenerated: true,
        status: 'active',
        createdAt: stamp
      }
    });
  }
}

async function main(event, context = cloud.getWXContext(), deps = {}) {
  if (!event.activityId) {
    throw businessError('activityId is required');
  }

  const db = deps.db || cloud.database();
  const openid = resolveOpenId(context, deps.getWXContext || (() => cloud.getWXContext()));
  const activityResult = await db.collection(COLLECTIONS.ACTIVITIES).doc(event.activityId).get();
  const activity = activityResult.data;

  if (!activity) {
    throw businessError('Activity not found');
  }

  if (activity.status === 'deleted') {
    throw businessError('Deleted activities cannot be edited');
  }

  const user = await getCurrentUser(db, openid);
  if (!canEditActivity(activity, user, openid)) {
    throw businessError('Only the organizer or an admin can edit this activity');
  }

  const teamsResult = await db
    .collection(COLLECTIONS.ACTIVITY_TEAMS)
    .where({ activityId: event.activityId })
    .get();
  const teams = teamsResult.data || [];
  const regularTeams = getRegularTeams(teams);
  const updateData = buildActivityUpdateData(event, activity, nowIso(deps.now));

  if (Number(updateData.signupLimitTotal) < Number(activity.joinedCount || 0)) {
    throw businessError('Total signup limit cannot be lower than joined players');
  }

  validateActivityDraft(buildValidationDraft(updateData, regularTeams));

  await syncBenchTeam(
    db,
    event.activityId,
    teams,
    Number(updateData.signupLimitTotal) || 0,
    updateData.updatedAt
  );

  await db.collection(COLLECTIONS.ACTIVITIES).doc(event.activityId).update({
    data: buildDatabaseUpdateData(db, updateData)
  });

  const changedFields = getChangedFields(activity, updateData);
  await db.collection(COLLECTIONS.ACTIVITY_LOGS).add({
    data: {
      activityId: event.activityId,
      operatorOpenId: openid,
      action: 'update_activity',
      changedFields,
      createdAt: updateData.updatedAt
    }
  });

  return {
    activityId: event.activityId,
    updated: true,
    changedFields
  };
}

module.exports = { main };
